from api_manage.settings.base import BASE_DIR

ALLOWED_HOSTS = ['*',
                 'www.megaseller.ru',
                 'megaseller.ru',
                 '31.31.198.29',
                 '127.0.0.1',
                 '192.168.1.37',
                 'localhost',
                 'www.localhost',
                 'aprelevka.localhost',
                 'balashiha.localhost',
                 'bronnitsy.localhost',
                 'chehov.localhost',
                 'chernogolovka.localhost',
                 'dmitrov.localhost',
                 'dolgoprudnyj.localhost',
                 'domodedovo.localhost',
                 'dubna.localhost',
                 'dzerzhinskij.localhost',
                 'egorevsk.localhost',
                 'elektrougli.localhost',
                 'himki.localhost',
                 'hotkovo.localhost',
                 'istra.localhost',
                 'ivanteevka.localhost',
                 'kashira.localhost',
                 'klimovsk.localhost',
                 'klin.localhost',
                 'kolomna.localhost',
                 'krasnoarmejsk.localhost',
                 'krasnogorsk.localhost',
                 'krasnoznamensk.localhost',
                 'kubinka.localhost',
                 'likino-dulevo.localhost',
                 'lobnya.localhost',
                 'lotoshino.localhost',
                 'luhovicy.localhost',
                 'lytkarino.localhost',
                 'lyubercy.localhost',
                 'mihnevo.localhost',
                 'mozhajsk.localhost',
                 'mytishchi.localhost',
                 'naro-fominsk.localhost',
                 'noginsk.localhost',
                 'cheboksary.localhost',
                 'dedovsk.localhost',
                 'elektrogorsk.localhost',
                 'elektrostal.localhost',
                 'fryanovo.localhost',
                 'fryazevo.localhost',
                 'fryazino.localhost',
                 'kazan.localhost',
                 'kolchugino.localhost',
                 'korolev.localhost',
                 'krasnozavodsk.localhost',
                 'kurovskoe.localhost',
                 'losino-petrov.localhost',
                 'monino.localhost',
                 'nahabino.localhost',
                 'nizhny-novgorod.localhost',
                 'odincovo.localhost',
                 'orekhovo-zuevo.localhost',
                 'ozery.localhost',
                 'ozherelie.localhost',
                 'pavlovskij-posad.localhost',
                 'peresvet.localhost',
                 'podolsk.localhost',
                 'protvino.localhost',
                 'pushkino.localhost',
                 'ramenskoe.localhost',
                 'reutov.localhost',
                 'roshal.localhost',
                 'ruza.localhost',
                 'saint-petersburg.localhost',
                 'samara.localhost',
                 'schelkovo.localhost',
                 'scherbinka.localhost',
                 'serebryannye-prudy.localhost',
                 'sergiev-posad.localhost',
                 'serpuhov.localhost',
                 'shahovskoe.localhost',
                 'shatura.localhost',
                 'shodnya.localhost',
                 'sofrino.localhost',
                 'solnechnogorsk.localhost',
                 'staraya-kupavna.localhost',
                 'stupino.localhost',
                 'taldom.localhost',
                 'troick.localhost',
                 'tuchkovo.localhost',
                 'vidnoe.localhost',
                 'volokolamsk.localhost',
                 'voskresensk.localhost',
                 'yahroma.localhost',
                 'zaraysk.localhost',
                 'zelenograd.localhost',
                 'zheleznodorogny.localhost',
                 'zhukovskij.localhost',
                 'zvenigorod.localhost',

                 ]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static/'  # for local dev, off on web
]

MEDIA_ROOT = BASE_DIR / 'media/'
MEDIA_URL = "/media/"

BASE_URL = 'localhost'
