# Generated by Django 5.0.2 on 2024-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_showed',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status_change',
            field=models.CharField(blank=True, default='18/03/2024 - 18:43:26', max_length=21, null=True, verbose_name='Время срабатывания'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_time_create',
            field=models.CharField(blank=True, default='18/03/2024 - 18:43:26', max_length=21, null=True, verbose_name='Время создания'),
        ),
    ]
