# Generated by Django 4.1 on 2024-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensor_sensor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status_change',
            field=models.CharField(blank=True, default='20/03/2024 - 14:50:37', max_length=21, null=True, verbose_name='Время срабатывания'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_time_create',
            field=models.CharField(blank=True, default='20/03/2024 - 14:50:37', max_length=21, null=True, verbose_name='Время создания'),
        ),
    ]
