# Generated by Django 4.1 on 2024-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_sensor_status_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=18, unique=True, verbose_name='Телефон')),
                ('client_name', models.CharField(blank=True, default='Клиент', max_length=50, null=True, verbose_name='Имя')),
                ('client_info', models.TextField(blank=True, default=' ', null=True, verbose_name='Описание')),
                ('client_email', models.EmailField(blank=True, default='client@mail.ru', max_length=255, null=True, verbose_name='Email')),
                ('client_time_create', models.CharField(blank=True, default='20/03/2024 - 15:21:11', max_length=21, null=True, verbose_name='Дата отправки')),
                ('client_ip_address', models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True, verbose_name='IP отправителя')),
                ('client_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
                'ordering': ['-client_time_create'],
            },
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status_change',
            field=models.CharField(blank=True, default='20/03/2024 - 15:21:11', max_length=21, null=True, verbose_name='Время срабатывания'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_time_create',
            field=models.CharField(blank=True, default='20/03/2024 - 15:21:11', max_length=21, null=True, verbose_name='Время создания'),
        ),
    ]
