# Generated by Django 4.1 on 2024-04-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_client_alter_sensor_sensor_status_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='Датчик')),
                ('sensor_MAC', models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='MAC-адрес датчика')),
                ('sensor_status_change', models.CharField(blank=True, default='12/04/2024 - 12:50:43', max_length=21, null=True, verbose_name='Время срабатывания')),
                ('sensor_status', models.CharField(choices=[('Unset', 'Не определено'), ('Alarm!', 'Тревога!'), ('Online', 'Онлайн')], default='Unset', max_length=10, verbose_name='Статус')),
                ('sensor_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Логи датчика',
                'verbose_name_plural': 'Логи датчика',
                'db_table': 'sensor_log',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_status_change',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_title',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_time_create',
            field=models.CharField(blank=True, default='12/04/2024 - 12:50:43', max_length=21, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status',
            field=models.CharField(choices=[('Unset', 'Не определено'), ('Alarm!', 'Тревога!'), ('Online', 'Онлайн')], default='Unset', max_length=10, verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_time_create',
            field=models.CharField(blank=True, default='12/04/2024 - 12:50:43', max_length=21, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_status_log',
            field=models.ForeignKey(blank=True, default=20, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensorlog', verbose_name='Событие датчика'),
        ),
    ]
