# Generated by Django 4.1 on 2024-04-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensorlog_alter_client_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_status_log',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='sensor_active',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_time_create',
            field=models.CharField(blank=True, default='12/04/2024 - 13:21:06', max_length=21, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_time_create',
            field=models.CharField(blank=True, default='12/04/2024 - 13:21:06', max_length=21, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='sensor_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='sensor_status_change',
            field=models.CharField(blank=True, default='12/04/2024 - 13:21:06', max_length=21, null=True, verbose_name='Время срабатывания'),
        ),
    ]
