# Generated by Django 5.0.1 on 2024-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='Site', max_length=250, null=True, verbose_name='Сайт')),
                ('user_name', models.CharField(blank=True, default='admin', max_length=250, null=True, verbose_name='Пользователь')),
                ('user_pass', models.CharField(blank=True, default='admin', max_length=250, null=True, verbose_name='Пароль')),
                ('token', models.CharField(blank=True, default='Token ', max_length=250, null=True, verbose_name='Токен')),
                ('project_name', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Имя проекта')),
                ('domain_name', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Домен')),
                ('region', models.TextField(blank=True, default=' ', null=True, verbose_name='Регион')),
                ('document_head', models.TextField(blank=True, default=' ', null=True, verbose_name='Блок head')),
                ('document_body', models.TextField(blank=True, default=' ', null=True, verbose_name='Блок body')),
                ('document_footer', models.TextField(blank=True, default=' ', null=True, verbose_name='Блок footer')),
                ('main_page_title', models.TextField(blank=True, default=' ', null=True, verbose_name='Title')),
                ('main_page_description', models.TextField(blank=True, default=' ', null=True, verbose_name='Description')),
                ('main_page_canonical', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Canonical')),
                ('contacts_address', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Адрес')),
                ('contacts_name', models.CharField(blank=True, default='Стиль потолка', max_length=250, null=True, verbose_name='Наименование')),
                ('contacts_tel', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Телефон')),
                ('contacts_tel_formatted', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Телефон формат')),
                ('contacts_whatsapp', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Ватсапп')),
                ('contacts_whatsapp_formatted', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Ватсапп формат')),
                ('contacts_telegram', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Телеграм')),
                ('contacts_telegram_formatted', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Телеграм формат')),
                ('contacts_email', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='E-mail')),
                ('contacts_email_formatted', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='E-mail формат')),
                ('contacts_map', models.TextField(blank=True, default=' ', null=True, verbose_name='Карта ПК-версия')),
                ('contacts_map_mobile', models.TextField(blank=True, default=' ', null=True, verbose_name='Карта мобильная версия')),
                ('requisites_company', models.CharField(blank=True, default='Стиль потолка', max_length=50, null=True, verbose_name='Название компании')),
                ('requisites_inn', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='ИНН')),
                ('requisites_work_hours', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Часы работы')),
                ('requisites_ogrn', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='ОГРН')),
                ('requisites_bank', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Банк')),
                ('requisites_bik', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Бик')),
                ('requisites_count', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Счет')),
                ('requisites_corr_count', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Корр. счет')),
                ('time_create', models.CharField(blank=True, default='08/02/2024 - 15:56:16', max_length=21, null=True, verbose_name='time_create')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'db_table': 'project',
                'ordering': ['-domain_name'],
            },
        ),
    ]
