# Generated by Django 4.1 on 2024-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='region',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='region_what',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='Регион, им. падеж'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='region_where',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='Регион, род. падеж'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='time_create',
            field=models.CharField(blank=True, default='15/02/2024 - 14:41:44', max_length=21, null=True, verbose_name='time_create'),
        ),
    ]
