# Generated by Django 4.1 on 2024-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_sitesettings_region_what_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='time_create',
            field=models.CharField(blank=True, default='20/03/2024 - 15:21:11', max_length=21, null=True, verbose_name='time_create'),
        ),
    ]
